name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SDL_VIDEODRIVER: dummy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 --count pgzero pgzrun.py test
    - name: Run tests
      run: |
        python setup.py test
